[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
auto_detect_solc = true
offline = true
optimizer = true
optimizer_runs = 200
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
